### PR TITLE
.editorconfig and some code cleanup

### PR DESCRIPTION
**Pull request by lucasmichot**
.editorconfig and code cleanup

### CODE REVIEW

**Comment by lucasmichot** [comment]
review plz @niklashof

**Comment by niklashof** [comment]
+

**Comment by lucasmichot** [comment]
check the hexo generate too, there are some warnings - but no hurry on that

**Comment by niklashof** [comment]
mmmh hexo generate seems to be fine in https://circleci.com/gh/trackfellas/blog/50 and https://circleci.com/gh/trackfellas/blog/51

**Comment by lucasmichot** [comment]
Damn - was on the wrong build (one related to blog) 
NVM :-)

**Pull request merged**
